# RENAME FILE TO 'config.yml'
bot:
  token: MTI1NzAwOTQ3ODA4NDIwMjY1OQ.Grt7HD.qP6sgq2R_X1zfc9QmFJU1ZeSbiKS-pLd3OSai8
  owner_ids:
    - 123456789123456789
    - 987654321987654321
  prefix: $
  default_bet: 100
  bonus_multiplier: 5 # bonus = default_bet * multiplier
  bonus_cooldown: 12 # Bonus every x hours
