# RENAME FILE TO 'config.yml'
bot:
  token: MTI1OTA2NjA3MTMxMTQ1MDE2Mw.GvARJ4.d11BqPV4i9IdMj9WWTi4oAiBdh0lj6PCNyjSNM
  owner_ids:
    - 123456789123456789
    - 987654321987654321
  prefix: $
  default_bet: 100
  bonus_multiplier: 5 # bonus = default_bet * multiplier
  bonus_cooldown: 12 # Bonus every x hours
